### ISSUE TITLE
Bundled issues

### ISSUE THREAD

**Issue by SergeySagan** [sabbirrahman/ng2-mdl#17]
Hey, when I try to bundle my app like this
```
"buildng": "npm run tsc && npm run browserify",
"tsc": "tsc -p .",
"browserify": "browserify -s main  wwwroot/js/main.js > wwwroot/js/bundle.js"
```
and I have it setup as instructed in my app.module (import, imports) and trying to use the progress deal... I am getting this error before the app even starts:

> Uncaught Error: Unexpected value 'Ng2MdlModule' imported by the module 'AppModule'
>     at https://localhost:44385/js/bundle.js:17111:37
>     at Array.forEach (native)
>     at CompileMetadataResolver.getNgModuleMetadata (https://localhost:44385/js/bundle.js:17096:46)
>     at RuntimeCompiler._compileComponents (https://localhost:44385/js/bundle.js:19817:49)
>     at RuntimeCompiler._compileModuleAndComponents (https://localhost:44385/js/bundle.js:19755:39)
>     at RuntimeCompiler.compileModuleAsync (https://localhost:44385/js/bundle.js:19746:23)
>     at PlatformRef_._bootstrapModuleWithZone (https://localhost:44385/js/bundle.js:27598:29)
>     at PlatformRef_.bootstrapModule (https://localhost:44385/js/bundle.js:27580:25)
>     at Object.374../app.module (https://localhost:44385/js/bundle.js:83232:53)
>     at s (https://localhost:44385/js/bundle.js:1:618)

**Comment by SergeySagan** [comment]
If you are having problems with this, give this a try: https://www.npmjs.com/package/angular2-mdl
